### ISSUE TITLE
implementation details: batch size=4

### ISSUE THREAD

**Issue by 7LFB** [ananyajana/fibrosis_bibe#1]
Dear author,
As mentioned in the paper, there are 7775 pathology image patches collecting from 30 patients. It means each patient has 7775/30 = 260 patches.
the training is done at the patient level, all the pathology image patches are fed into the network for training. 
the batch size =4. does it mean 4 patients?  If so,   4x260 =1040 image patches are fed into the network every step?

**Comment by ananyajana** [comment]
Hi,

The number of CT slices of pathology patches per patient is not the same. These numbers vary  e.g. for a patient A the number of CT slices could be 41 whereas for patient B the number of CT slices could be 35.
Yes, Batch size = 4 means we will use 4 patients each time.
Please let me know if this helps or if you have further questions.

**Comment by 7LFB** [comment]
It's very clear. Thanks a lot.
